/*
Nombre: Edwing Ricardo Rochin López
Descripción: Clase de creación para productos
Fecha: 15/09/2022
 */
package Vista;

import static Controlador.ProductsController.InsertProduct;
import Modelo.ProductsModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin
 */
public class CreateProductsView extends javax.swing.JFrame {
    boolean editing = false;
    public CreateProductsView() {
        initComponents();
        this.setLocationRelativeTo(null);
        BtnAddPro.setText("Agregar");
        txtIdProducts.setVisible(false);
    }

    /**
     * Creates new form CreateProductsView
     */
    public CreateProductsView(ProductsModel products) {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdProducts.setText(String.valueOf(products.idProductos));
        txtNameProduct.setText(products.NombreProducto);
        txtDesProduct.setText(products.Descripcion);
        txtPreProduct.setText(String.valueOf(products.PrecioProducto));
        
        txtIdProducts.setVisible(false);
        BtnAddPro.setText("Editar");
        editing = true;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloPro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtIdProducts = new javax.swing.JTextField();
        BtnAddPro = new javax.swing.JButton();
        BtnCancelPro = new javax.swing.JButton();
        txtPreProduct = new javax.swing.JTextField();
        lblPreProduct = new javax.swing.JLabel();
        txtNameProduct = new javax.swing.JTextField();
        lblNameProduct = new javax.swing.JLabel();
        txtDesProduct = new javax.swing.JTextField();
        lblDesProduct = new javax.swing.JLabel();
        jSp3 = new javax.swing.JSeparator();
        jSp2 = new javax.swing.JSeparator();
        jSp1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 102, 11));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPro.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblTituloPro.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPro.setText("Agregar Producto");
        jPanel2.add(lblTituloPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdProducts.setEditable(false);
        jPanel3.add(txtIdProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 30, 20));

        BtnAddPro.setBackground(new java.awt.Color(204, 102, 11));
        BtnAddPro.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        BtnAddPro.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddPro.setText("Agregar");
        BtnAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddProActionPerformed(evt);
            }
        });
        jPanel3.add(BtnAddPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 120, 40));

        BtnCancelPro.setBackground(new java.awt.Color(204, 102, 11));
        BtnCancelPro.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        BtnCancelPro.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelPro.setText("Cancelar");
        BtnCancelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelProActionPerformed(evt);
            }
        });
        jPanel3.add(BtnCancelPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 120, 40));

        txtPreProduct.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtPreProduct.setBorder(null);
        txtPreProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPreProductKeyTyped(evt);
            }
        });
        jPanel3.add(txtPreProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 490, 30));

        lblPreProduct.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblPreProduct.setForeground(new java.awt.Color(204, 102, 11));
        lblPreProduct.setText("Precio:");
        jPanel3.add(lblPreProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtNameProduct.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtNameProduct.setBorder(null);
        jPanel3.add(txtNameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 490, 30));

        lblNameProduct.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblNameProduct.setForeground(new java.awt.Color(204, 102, 11));
        lblNameProduct.setText("Nombre:");
        jPanel3.add(lblNameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        txtDesProduct.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtDesProduct.setBorder(null);
        jPanel3.add(txtDesProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 490, 30));

        lblDesProduct.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblDesProduct.setForeground(new java.awt.Color(204, 102, 11));
        lblDesProduct.setText("Descripción:");
        jPanel3.add(lblDesProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jSp3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 490, 20));

        jSp2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 490, 20));

        jSp1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 490, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 730, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddProActionPerformed
        ProductsModel newPro = new ProductsModel();
        String NombreProducto = txtNameProduct.getText();
        String Descripcion = txtDesProduct.getText();
        String PrecioProducto = txtPreProduct.getText();
        
        if((!NombreProducto.isBlank() || !NombreProducto.isEmpty()) &&
           (!Descripcion.isBlank() || !Descripcion.isEmpty()) &&
           (!PrecioProducto.isBlank() || !PrecioProducto.isEmpty())){
            
                newPro.NombreProducto = txtNameProduct.getText();
                newPro.Descripcion = txtDesProduct.getText();
                newPro.PrecioProducto =  Double.parseDouble(txtPreProduct.getText());        

                if(editing)
                {
                    newPro.idProductos = Integer.parseInt(txtIdProducts.getText());
                }

                boolean correct = InsertProduct(newPro, editing);

                if(correct)
                {
                    JOptionPane.showMessageDialog(null, "El producto se guardo correctamente.");
                    super.dispose();
                }
        }
        else{
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
        }
    }//GEN-LAST:event_BtnAddProActionPerformed

    private void BtnCancelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelProActionPerformed
        super.dispose();
    }//GEN-LAST:event_BtnCancelProActionPerformed

    private void txtPreProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreProductKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtPreProductKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateProductsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateProductsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateProductsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateProductsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CreateProductsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddPro;
    private javax.swing.JButton BtnCancelPro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSp1;
    private javax.swing.JSeparator jSp2;
    private javax.swing.JSeparator jSp3;
    private javax.swing.JLabel lblDesProduct;
    private javax.swing.JLabel lblNameProduct;
    private javax.swing.JLabel lblPreProduct;
    private javax.swing.JLabel lblTituloPro;
    private javax.swing.JTextField txtDesProduct;
    private javax.swing.JTextField txtIdProducts;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtPreProduct;
    // End of variables declaration//GEN-END:variables
}
