/*
Nombre: Edwing Ricardo Rochin López
Descripción: Clase de creación para clientes
Fecha: 15/09/2022
 */
package Vista;

import static Controlador.ClientController.InsertClient;
import Modelo.ClientModel;
import javax.swing.JOptionPane;

public class CreateClientView extends javax.swing.JFrame {
    boolean editing = false;
    public CreateClientView() {
        initComponents();
        this.setLocationRelativeTo(null);
        BtnAddClient.setText("Agregar");
        txtIdClient.setVisible(false);
    }

public CreateClientView(ClientModel client) {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdClient.setText(String.valueOf(client.idCliente));
        txtNameClient.setText(client.NombreCli);
        txtRFC.setText(client.RFC);
        txtMailCli.setText(String.valueOf(client.CorreoCliente));
        txtTelefonoCli.setText(client.TelefonoCliente);
        txtDirectionCli.setText(client.DireccionCliente);
        
        txtIdClient.setVisible(false);
        BtnAddClient.setText("Editar");
        editing = true;        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        BtnAgregarEmp = new javax.swing.JButton();
        txtCalleNumAg = new javax.swing.JTextField();
        txtNEmployeesAg = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblNameEmployee = new javax.swing.JLabel();
        lblCalleNum = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtIdEmployee = new javax.swing.JTextField();
        BtnCancel = new javax.swing.JButton();
        lblNumSS = new javax.swing.JLabel();
        txtNumSS = new javax.swing.JTextField();
        lblColonia = new javax.swing.JLabel();
        btnColonia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTituloCli = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtIdClient = new javax.swing.JTextField();
        BtnAddClient = new javax.swing.JButton();
        BtnCancelClient = new javax.swing.JButton();
        txtDirectionCli = new javax.swing.JTextField();
        lblRFC = new javax.swing.JLabel();
        txtNameClient = new javax.swing.JTextField();
        lblDirectionCli = new javax.swing.JLabel();
        jSc1 = new javax.swing.JSeparator();
        jSc2 = new javax.swing.JSeparator();
        lblNameClient1 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        txtMailCli = new javax.swing.JTextField();
        txtTelefonoCli = new javax.swing.JTextField();
        jSc3 = new javax.swing.JSeparator();
        jSc4 = new javax.swing.JSeparator();
        jSc5 = new javax.swing.JSeparator();
        lblMailCli = new javax.swing.JLabel();
        lblTelefonoCli = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnAgregarEmp.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        BtnAgregarEmp.setText("Agregar");
        BtnAgregarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarEmpActionPerformed(evt);
            }
        });

        txtCalleNumAg.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        txtNEmployeesAg.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        lblNameEmployee.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblNameEmployee.setText("Nombre Empleado:");

        lblCalleNum.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblCalleNum.setText("Calle y Número:");

        lblUserName.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblUserName.setText("Nombre Usuario:");

        txtIdEmployee.setEditable(false);

        BtnCancel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        BtnCancel.setText("Cancelar");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        lblNumSS.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblNumSS.setText("Número de Seguro Social:");

        txtNumSS.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtNumSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumSSActionPerformed(evt);
            }
        });

        lblColonia.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblColonia.setText("Colonia");

        btnColonia.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btnColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColoniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCalleNumAg, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNameEmployee)
                                        .addComponent(lblCalleNum)
                                        .addComponent(lblUserName)
                                        .addComponent(txtNEmployeesAg, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNumSS)
                                    .addComponent(txtNumSS, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblColonia)))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(BtnAgregarEmp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCancel)))))
                .addGap(50, 50, 50))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(lblNameEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNEmployeesAg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCalleNum)
                        .addGap(11, 11, 11)
                        .addComponent(txtCalleNumAg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(lblNumSS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblColonia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarEmp)
                    .addComponent(BtnCancel))
                .addGap(24, 24, 24)
                .addComponent(txtIdEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 102, 11));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloCli.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblTituloCli.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCli.setText("Agregar Cliente");
        jPanel3.add(lblTituloCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 120));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdClient.setEditable(false);
        jPanel4.add(txtIdClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 40, -1));

        BtnAddClient.setBackground(new java.awt.Color(204, 102, 11));
        BtnAddClient.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        BtnAddClient.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddClient.setText("Agregar");
        BtnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddClientActionPerformed(evt);
            }
        });
        jPanel4.add(BtnAddClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 120, 40));

        BtnCancelClient.setBackground(new java.awt.Color(204, 102, 11));
        BtnCancelClient.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        BtnCancelClient.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelClient.setText("Cancelar");
        BtnCancelClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelClientActionPerformed(evt);
            }
        });
        jPanel4.add(BtnCancelClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 120, 40));

        txtDirectionCli.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtDirectionCli.setBorder(null);
        jPanel4.add(txtDirectionCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 490, 30));

        lblRFC.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblRFC.setForeground(new java.awt.Color(204, 102, 11));
        lblRFC.setText("RFC:");
        jPanel4.add(lblRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtNameClient.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtNameClient.setBorder(null);
        jPanel4.add(txtNameClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 490, 30));

        lblDirectionCli.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblDirectionCli.setForeground(new java.awt.Color(204, 102, 11));
        lblDirectionCli.setText("Dirección:");
        jPanel4.add(lblDirectionCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jSc1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 490, 20));

        jSc2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 490, 20));

        lblNameClient1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblNameClient1.setForeground(new java.awt.Color(204, 102, 11));
        lblNameClient1.setText("Nombre:");
        jPanel4.add(lblNameClient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        txtRFC.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtRFC.setBorder(null);
        jPanel4.add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 490, 30));

        txtMailCli.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtMailCli.setBorder(null);
        jPanel4.add(txtMailCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 490, 30));

        txtTelefonoCli.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtTelefonoCli.setBorder(null);
        jPanel4.add(txtTelefonoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 490, 30));

        jSc3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 490, 20));

        jSc4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 490, 20));

        jSc5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 490, 20));

        lblMailCli.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblMailCli.setForeground(new java.awt.Color(204, 102, 11));
        lblMailCli.setText("Correo:");
        jPanel4.add(lblMailCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        lblTelefonoCli.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lblTelefonoCli.setForeground(new java.awt.Color(204, 102, 11));
        lblTelefonoCli.setText("Telefono:");
        jPanel4.add(lblTelefonoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 730, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarEmpActionPerformed

    }//GEN-LAST:event_BtnAgregarEmpActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        super.dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void txtNumSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumSSActionPerformed

    private void btnColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColoniaActionPerformed

    private void BtnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddClientActionPerformed
        ClientModel newClient = new ClientModel();
        String NombreCli = txtNameClient.getText();
        String RFC = txtRFC.getText();
        String CorreoCliente = txtMailCli.getText();
        String DireccionCliente = txtDirectionCli.getText();
        String TelefonoCliente = txtTelefonoCli.getText();
        
        if((!NombreCli.isBlank() || !NombreCli.isEmpty()) &&
            (!RFC.isBlank() || !RFC.isEmpty()) &&
            (!CorreoCliente.isBlank() || !CorreoCliente.isEmpty()) &&
            (!DireccionCliente.isBlank() || !DireccionCliente.isEmpty()) &&
            (!TelefonoCliente.isBlank() || !TelefonoCliente.isEmpty())){
                newClient.NombreCli = txtNameClient.getText();
                newClient.RFC = txtRFC.getText();
                newClient.CorreoCliente = txtMailCli.getText();
                newClient.TelefonoCliente = txtTelefonoCli.getText();
                newClient.DireccionCliente = txtDirectionCli.getText();

                if(editing)
                {
                    newClient.idCliente = Integer.parseInt(txtIdClient.getText());
                }

                boolean correct = InsertClient(newClient, editing);

                if(correct)
                {
                    JOptionPane.showMessageDialog(null, "El cliente se guardo correctamente.");
                    super.dispose();
                }
        }
        else{
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        }

        
    }//GEN-LAST:event_BtnAddClientActionPerformed

    private void BtnCancelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelClientActionPerformed
        super.dispose();
    }//GEN-LAST:event_BtnCancelClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddClient;
    private javax.swing.JButton BtnAgregarEmp;
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnCancelClient;
    private javax.swing.JTextField btnColonia;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSc1;
    private javax.swing.JSeparator jSc2;
    private javax.swing.JSeparator jSc3;
    private javax.swing.JSeparator jSc4;
    private javax.swing.JSeparator jSc5;
    private javax.swing.JLabel lblCalleNum;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblDirectionCli;
    private javax.swing.JLabel lblMailCli;
    private javax.swing.JLabel lblNameClient1;
    private javax.swing.JLabel lblNameEmployee;
    private javax.swing.JLabel lblNumSS;
    private javax.swing.JLabel lblRFC;
    private javax.swing.JLabel lblTelefonoCli;
    private javax.swing.JLabel lblTituloCli;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtCalleNumAg;
    private javax.swing.JTextField txtDirectionCli;
    private javax.swing.JTextField txtIdClient;
    private javax.swing.JTextField txtIdEmployee;
    private javax.swing.JTextField txtMailCli;
    private javax.swing.JTextField txtNEmployeesAg;
    private javax.swing.JTextField txtNameClient;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNumSS;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefonoCli;
    // End of variables declaration//GEN-END:variables
}
