/*
Nombre: Edwing Ricardo Rochin López
Descripción: Clase de creación para ordenes
Fecha: 15/09/2022
 */
package Vista;

import static Controlador.ClientController.GetClient;
import static Controlador.EmployeesController.GetPositions;
import static Controlador.EmployeesController.InsertEmployees;
import Controlador.OrderController;
import static Controlador.OrderController.GetPrice;
import static Controlador.OrderController.GetPriceSupply;
import static Controlador.OrderController.InsertOrders;
import Modelo.ClientModel;
import Modelo.EmployeeModel;
import Modelo.OrderCreateModel;
import Modelo.PositionModel;
import Modelo.ProductsModel;
import Modelo.SuppliesModel;
import java.awt.List;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edwin
 */
public class CreateOrderView extends javax.swing.JFrame {

    EmployeeModel employeeS = new EmployeeModel();
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<SuppliesModel> supplyList = new ArrayList<>();
    ArrayList<ProductsModel> productList = new ArrayList<>();
    
    public CreateOrderView() {
        initComponents();
    }
    //Método para crear la orden
    public CreateOrderView(EmployeeModel employee) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        employeeS = employee;
        cBoxClient.addItem("Seleccione uno...");
        cBoxProducto.addItem("Seleccione uno...");
        cBoxIngr1.addItem("Seleccione uno...");
        cBoxIngr2.addItem("Seleccione uno...");
        cBoxIngr3.addItem("Seleccione uno...");
        
        LoadClients();
        LoadProducts();
        LoadSupplies();
        
        txtCantidad.setText("1");
        
        cBoxIngr1.setEnabled(false);
        cBoxIngr2.setEnabled(false);
        cBoxIngr3.setEnabled(false);
        
        modelo.addColumn("Cliente");
        modelo.addColumn("Producto");
        modelo.addColumn("Ingrediente 1");
        modelo.addColumn("Ingrediente 2");
        modelo.addColumn("Ingrediente 3");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Valor $");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cBoxClient = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cBoxProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblIngr1 = new javax.swing.JLabel();
        cBoxIngr1 = new javax.swing.JComboBox<>();
        lblIngr2 = new javax.swing.JLabel();
        cBoxIngr2 = new javax.swing.JComboBox<>();
        lblIngr3 = new javax.swing.JLabel();
        cBoxIngr3 = new javax.swing.JComboBox<>();
        btnAddProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnSaveOrder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTituloPro = new javax.swing.JLabel();
        BtnCancel1 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 11));
        jLabel1.setText("Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        cBoxClient.setBackground(new java.awt.Color(204, 102, 11));
        cBoxClient.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(cBoxClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 620, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 11));
        jLabel2.setText("Producto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        cBoxProducto.setBackground(new java.awt.Color(204, 102, 11));
        cBoxProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cBoxProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBoxProductoItemStateChanged(evt);
            }
        });
        cBoxProducto.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cBoxProductoVetoableChange(evt);
            }
        });
        jPanel1.add(cBoxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 440, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 11));
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 160, 30));

        lblIngr1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblIngr1.setForeground(new java.awt.Color(204, 102, 11));
        lblIngr1.setText("Ingrediente 1:");
        jPanel1.add(lblIngr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        cBoxIngr1.setBackground(new java.awt.Color(204, 102, 11));
        cBoxIngr1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cBoxIngr1.setToolTipText("");
        jPanel1.add(cBoxIngr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 170, 30));

        lblIngr2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblIngr2.setForeground(new java.awt.Color(204, 102, 11));
        lblIngr2.setText("Ingrediente 2:");
        jPanel1.add(lblIngr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        cBoxIngr2.setBackground(new java.awt.Color(204, 102, 11));
        cBoxIngr2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(cBoxIngr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 170, 30));

        lblIngr3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblIngr3.setForeground(new java.awt.Color(204, 102, 11));
        lblIngr3.setText("Ingrediente 3:");
        jPanel1.add(lblIngr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        cBoxIngr3.setBackground(new java.awt.Color(204, 102, 11));
        cBoxIngr3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(cBoxIngr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 180, 30));

        btnAddProduct.setBackground(new java.awt.Color(204, 102, 11));
        btnAddProduct.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("Agregar");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 120, 30));

        jTable1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(204, 102, 11));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 630, 220));

        BtnSaveOrder.setBackground(new java.awt.Color(204, 102, 11));
        BtnSaveOrder.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtnSaveOrder.setForeground(new java.awt.Color(255, 255, 255));
        BtnSaveOrder.setText("Guardar");
        BtnSaveOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveOrderActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSaveOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 120, 30));

        jPanel3.setBackground(new java.awt.Color(204, 102, 11));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPro.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblTituloPro.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPro.setText("Toma de la Orden");
        jPanel3.add(lblTituloPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 80));

        BtnCancel1.setBackground(new java.awt.Color(204, 102, 11));
        BtnCancel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BtnCancel1.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancel1.setText("Cancelar");
        BtnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancel1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 120, 30));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("Total...");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 90, -1));

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 590, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBoxProductoItemStateChanged
        //Implementación de los productos en el combo
        String product = (String)cBoxProducto.getSelectedItem();

        if(product.equals("3-Pizza Mixta")){
            cBoxIngr1.setEnabled(true);
            cBoxIngr2.setEnabled(true);
            cBoxIngr3.setEnabled(true);
        }
        else{
            cBoxIngr1.setEnabled(false);
            cBoxIngr2.setEnabled(false);
            cBoxIngr3.setEnabled(false);
        }
    }//GEN-LAST:event_cBoxProductoItemStateChanged

    private void cBoxProductoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cBoxProductoVetoableChange

    }//GEN-LAST:event_cBoxProductoVetoableChange

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed

    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        String client = (String)cBoxClient.getSelectedItem();
        String product = (String)cBoxProducto.getSelectedItem();
        int cantidad = Integer.parseInt(txtCantidad.getText());
        Object[] newRow = new Object[7];       
        
        if(client.equals("Seleccione uno...")){
            JOptionPane.showMessageDialog(null, "Necesita seleccionar un cliente");
        }
        else if(product.equals("Seleccione uno...")){
            JOptionPane.showMessageDialog(null, "Necesita seleccionar un producto");
        }
        else if(cantidad <= 0){
            JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor a 0");
        }
        else{
            String position = (String)cBoxProducto.getSelectedItem();
            String[] parts = position.split("-");
            int idProducto = Integer.parseInt(parts[0]) ;

            newRow[0] = client;
            newRow[1] = product;
            newRow[2] = "";
            newRow[3] = "";
            newRow[4] = "";
            newRow[5] = cantidad;
            newRow[6] = GetPrice(idProducto) * cantidad;
        
            if(product.equals("3-Pizza Mixta"))
            {
                String ingr1 = (String)cBoxIngr1.getSelectedItem();
                String ingr2 = (String)cBoxIngr2.getSelectedItem();
                String ingr3 = (String)cBoxIngr3.getSelectedItem();

                if(!ingr1.equals("Seleccione uno..."))
                {
                    newRow[6] = ((double)newRow[6] + GetPriceSupply(GetID(ingr1)) * cantidad);
                    newRow[2] = (String)cBoxIngr1.getSelectedItem();
                }
                if(!ingr2.equals("Seleccione uno..."))
                {
                    newRow[6] = ((double)newRow[6] + GetPriceSupply(GetID(ingr2)) * cantidad);
                    newRow[3] = (String)cBoxIngr2.getSelectedItem();
                }
                if(!ingr3.equals("Seleccione uno..."))
                {
                    newRow[6] = ((double)newRow[6] + GetPriceSupply(GetID(ingr3)) * cantidad);
                    newRow[4] = (String)cBoxIngr3.getSelectedItem();
                }
            }

            modelo.addRow(newRow);
            jTable1.setModel(modelo);
            
            double total = 0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                total = (total + Double.parseDouble(jTable1.getValueAt(i, 6)+""));
            }
            lblGrandTotal.setText("$"+total+"mx");
        }        
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void BtnSaveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveOrderActionPerformed
        //Guardar comanda
        ArrayList<OrderCreateModel> orderList = new ArrayList<OrderCreateModel>();
        double total = 0;
        int row = modelo.getRowCount();
        
        if(row > 0)
        {
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                OrderCreateModel newOrder = new OrderCreateModel();
                newOrder.Cliente = String.valueOf(jTable1.getValueAt(i, 0));
                newOrder.Producto = String.valueOf(jTable1.getValueAt(i, 1));
                newOrder.Ingrediente1 = String.valueOf(jTable1.getValueAt(i, 2));
                newOrder.Ingrediente2 = String.valueOf(jTable1.getValueAt(i, 3));
                newOrder.Ingrediente3 = String.valueOf(jTable1.getValueAt(i, 4));
                newOrder.Cantidad = Integer.parseInt(jTable1.getValueAt(i, 5)+"");
                newOrder.ValorProducto = Double.parseDouble(jTable1.getValueAt(i, 6)+"");      
                total = (total + Double.parseDouble(jTable1.getValueAt(i, 6)+""));
                
                orderList.add(newOrder);
            }
        
            boolean correct = InsertOrders(orderList, employeeS.idEmpleado, total);

            if(correct)
            {
                JOptionPane.showMessageDialog(null, "La comanda se registro con exito.");
                super.dispose();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Necesita agregar elementos a la comanda");
        }
    }//GEN-LAST:event_BtnSaveOrderActionPerformed

    private void BtnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancel1ActionPerformed
        super.dispose();
    }//GEN-LAST:event_BtnCancel1ActionPerformed

    public int GetID(String itemX){        
        String[] parts = itemX.split("-");
        int id = Integer.parseInt(parts[0]) ;
        
        return id;
    }
    
    /**
     * @param args the command line arguments
     */
    
    public void LoadClients(){
        ArrayList<ClientModel> clientList = GetClient();
                
        for(ClientModel cli: clientList)
        {
                cBoxClient.addItem(cli.idCliente +"-"+ cli.NombreCli);
        }        
    }
    
    public void LoadProducts()
    {
        productList = OrderController.GetProducts();
                
        for(ProductsModel pro: productList)
        {
            cBoxProducto.addItem(pro.idProductos +"-"+ pro.NombreProducto);
        }  
    }
    
    public void LoadSupplies()
    {
        supplyList = OrderController.GetSupplies();
                
        for(SuppliesModel sup: supplyList)
        {
            cBoxIngr1.addItem(sup.idInsumos +"-"+ sup.NombreInsumo);
            cBoxIngr2.addItem(sup.idInsumos +"-"+ sup.NombreInsumo);
            cBoxIngr3.addItem(sup.idInsumos +"-"+ sup.NombreInsumo);
        }  
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateOrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel1;
    private javax.swing.JButton BtnSaveOrder;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JComboBox<String> cBoxClient;
    private javax.swing.JComboBox<String> cBoxIngr1;
    private javax.swing.JComboBox<String> cBoxIngr2;
    private javax.swing.JComboBox<String> cBoxIngr3;
    private javax.swing.JComboBox<String> cBoxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblIngr1;
    private javax.swing.JLabel lblIngr2;
    private javax.swing.JLabel lblIngr3;
    private javax.swing.JLabel lblTituloPro;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
