/*
Nombre: Edwing Ricardo Rochin López
Descripción: Clase para agregar empleados
Fecha: 15/09/2022
 */
package Vista;

//import static Vista.MainWindow.Reproductor;
import static Controlador.EmployeesController.DeleteEmployees;
import static Controlador.EmployeesController.existsEmployees;
import static Controlador.EmployeesController.GetEmployees;
import Modelo.EmployeeModel;
import com.mysql.cj.util.StringUtils;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edwin
 */
public class EmployeeView extends javax.swing.JPanel {

    /**
     * Creates new form JPEmployee
     */
DefaultTableModel modelo = new DefaultTableModel();
//JTable tabla = new JTable(modelo);
    
    public EmployeeView() {
        initComponents();
        
        GetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdEmployee = new javax.swing.JTable();
        txtIdEmpleado = new javax.swing.JTextField();
        btnDeleteEmp = new javax.swing.JButton();
        btnUpdateEmp = new javax.swing.JButton();
        btnAddEmployee = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTituloEmp = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpd.setBackground(new java.awt.Color(204, 102, 11));
        btnUpd.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpd.setForeground(new java.awt.Color(255, 255, 255));
        btnUpd.setText("Actualizar");
        btnUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        grdEmployee.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        grdEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grdEmployee.setGridColor(new java.awt.Color(204, 102, 11));
        grdEmployee.setSelectionBackground(new java.awt.Color(204, 102, 11));
        grdEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdEmployeeMouseClicked(evt);
            }
        });
        grdEmployee.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                grdEmployeePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(grdEmployee);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 650, 360));

        txtIdEmpleado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });
        txtIdEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdEmpleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdEmpleadoKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 30));

        btnDeleteEmp.setBackground(new java.awt.Color(204, 102, 11));
        btnDeleteEmp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDeleteEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEmp.setText("Eliminar");
        btnDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 100, 30));

        btnUpdateEmp.setBackground(new java.awt.Color(204, 102, 11));
        btnUpdateEmp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpdateEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateEmp.setText("Editar");
        btnUpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 100, 30));

        btnAddEmployee.setBackground(new java.awt.Color(204, 102, 11));
        btnAddEmployee.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAddEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmployee.setText("Agregar");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, 30));

        jPanel2.setBackground(new java.awt.Color(204, 102, 11));

        lblTituloEmp.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTituloEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloEmp.setText("Apartado de Empleados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblTituloEmp)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTituloEmp)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdActionPerformed
        modelo = new DefaultTableModel();
        grdEmployee.setModel(modelo);
        
        GetData();
    }//GEN-LAST:event_btnUpdActionPerformed

    private void grdEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdEmployeeMouseClicked
        //Object codigo = modelo.getValueAt(tabla.getSelectedRow(), 0);

        //System.out.println("el id seleccionado es: "+codigo);
    }//GEN-LAST:event_grdEmployeeMouseClicked

    private void grdEmployeePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_grdEmployeePropertyChange

    }//GEN-LAST:event_grdEmployeePropertyChange

    private void txtIdEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEmpleadoKeyPressed

    }//GEN-LAST:event_txtIdEmpleadoKeyPressed

    private void txtIdEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdEmpleadoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdEmpleadoKeyTyped

    private void btnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmpActionPerformed
        //Eliminación de datos
        int idEmployee = Integer.parseInt(txtIdEmpleado.getText());

        boolean corret = DeleteEmployees(idEmployee);

        if(corret)
        {
            JOptionPane.showMessageDialog(null, "Se elimino el IdEmpleado " +idEmployee+ "correctamente.");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "El empleado no existe, intentelo de nuevo.");
        }
    }//GEN-LAST:event_btnDeleteEmpActionPerformed

    private void btnUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEmpActionPerformed
        //Edición de datos
        int idEmployee = 0;

        if(!StringUtils.isNullOrEmpty(txtIdEmpleado.getText()))
        {
            idEmployee = Integer.parseInt(txtIdEmpleado.getText());

            EmployeeModel employee = existsEmployees(idEmployee);

            if(employee.idEmpleado == idEmployee){
                new CreateEmployeeView(employee).setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "El empleado que intentas editar no existe, intentelo de nuevo.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Es necesario ingresar un idEmpleado para editar.");
        }
    }//GEN-LAST:event_btnUpdateEmpActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        new CreateEmployeeView().setVisible(true);
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed
    //Obtención de datos
    public void GetData()
    {
        ArrayList<EmployeeModel> employeeList = GetEmployees();
        //aqui vas a limpiar el grid, antes de cargarle el modelo
        grdEmployee.setModel(modelo);
        
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Dirección");
        modelo.addColumn("Numero SS");
        modelo.addColumn("Colonia");
        //modelo.addColumn("Fecha Contrato");
        modelo.addColumn("Nombre Usuario");
        modelo.addColumn("Password");
        modelo.addColumn("Puesto");
        
        for(EmployeeModel emp: employeeList)
            {
                 Object[] filas2 = new Object[8];//9
                 filas2[0] = emp.idEmpleado;
                 filas2[1] = emp.NombreEmp;
                 filas2[2] = emp.CalleNumero;
                 filas2[3] = emp.NumeroSS;
                 filas2[4] = emp.Colonia;
                 //filas2[4] = emp.FechaContrato;
                 filas2[5] = emp.NombreUsuario;
                 filas2[6] = emp.Password;
                 filas2[7] = emp.NombreP;
                 
                 modelo.addRow(filas2);
            }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnDeleteEmp;
    private javax.swing.JButton btnUpd;
    private javax.swing.JButton btnUpdateEmp;
    private javax.swing.JTable grdEmployee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloEmp;
    private javax.swing.JTextField txtIdEmpleado;
    // End of variables declaration//GEN-END:variables
}
