/*
Nombre: Edwing Ricardo Rochin López
Descripción: Clase principal para MainWindow
Fecha: 15/09/2022
 */
package Vista;

import Modelo.EmployeeModel;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Edwin
 */
public class MainWindow extends javax.swing.JFrame {

    EmployeeModel employeeS = new EmployeeModel();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    //Metdo para iniciar la vista de la ventana según los privilegios del usuario
    public MainWindow(EmployeeModel employee) {
        initComponents();
        this.setLocationRelativeTo(null);
        employeeS = employee;
        
        lblMain.setVisible(false);
        btnOrder.setVisible(false);
        lblEmpleados.setVisible(false);
        btnEmployees.setVisible(false);
        lblClientes.setVisible(false);
        btnClient.setVisible(false);
        lblProductos.setVisible(false);
        btnProducts.setVisible(false);
        lblInsumos.setVisible(false);
        btnSupplies.setVisible(false);
        
        lblWelcome.setText("Bienvenido a la aplicación: " + employee.NombreEmp);
        lblUser.setText(employee.NombreEmp);
        
        switch (employee.idPuesto){
            case 1:
                lblMain.setVisible(true);
                btnOrder.setVisible(true);
                lblEmpleados.setVisible(true);
                btnEmployees.setVisible(true);
                lblClientes.setVisible(true);
                btnClient.setVisible(true);
                lblProductos.setVisible(true);
                btnProducts.setVisible(true);
                lblInsumos.setVisible(true);
                btnSupplies.setVisible(true);
            break;
            case 2:
                lblMain.setVisible(true);
                btnOrder.setVisible(true);
                lblClientes.setVisible(true);
                btnClient.setVisible(true);
            break;
            case 3:
                lblMain.setVisible(true);
                btnOrder.setVisible(true);
                lblEmpleados.setVisible(true);
                btnEmployees.setVisible(true);
                lblClientes.setVisible(true);
                btnClient.setVisible(true);
                lblProductos.setVisible(true);
                btnProducts.setVisible(true);
                lblInsumos.setVisible(true);
                btnSupplies.setVisible(true);
            break;
            case 4:
                lblProductos.setVisible(true);
                btnProducts.setVisible(true);
                lblInsumos.setVisible(true);
                btnSupplies.setVisible(true);
                
                lblProductos.setLocation(0, 170);
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuIzq = new javax.swing.JPanel();
        btnSupplies = new javax.swing.JPanel();
        lblInsumos = new javax.swing.JLabel();
        iconSupplbl = new javax.swing.JLabel();
        btnOrder = new javax.swing.JPanel();
        iconOrderlbl = new javax.swing.JLabel();
        lblComanda1 = new javax.swing.JLabel();
        btnEmployees = new javax.swing.JPanel();
        lblEmpleados = new javax.swing.JLabel();
        iconEmployeelbl = new javax.swing.JLabel();
        btnClient = new javax.swing.JPanel();
        lblClientes = new javax.swing.JLabel();
        iconClientlbl = new javax.swing.JLabel();
        btnProducts = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCloseS = new javax.swing.JPanel();
        liblCloseS = new javax.swing.JLabel();
        iconExitlbl = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        iconUserlbl = new javax.swing.JLabel();
        btnMain = new javax.swing.JPanel();
        lblMain = new javax.swing.JLabel();
        iconMainlbl = new javax.swing.JLabel();
        lblLetras = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        liblTextoM = new javax.swing.JLabel();
        Reproductor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuIzq.setBackground(new java.awt.Color(204, 102, 11));
        menuIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSupplies.setBackground(new java.awt.Color(209, 114, 28));
        btnSupplies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupplies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuppliesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuppliesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSuppliesMousePressed(evt);
            }
        });
        btnSupplies.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInsumos.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblInsumos.setForeground(new java.awt.Color(255, 255, 255));
        lblInsumos.setText("Insumos");
        lblInsumos.setPreferredSize(new java.awt.Dimension(190, 50));
        btnSupplies.add(lblInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 108, 38));

        iconSupplbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMainWindow/iconSupp.png"))); // NOI18N
        btnSupplies.add(iconSupplbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        menuIzq.add(btnSupplies, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 210, 55));

        btnOrder.setBackground(new java.awt.Color(209, 114, 28));
        btnOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOrderMousePressed(evt);
            }
        });
        btnOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconOrderlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMainWindow/iconOrder.png"))); // NOI18N
        btnOrder.add(iconOrderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblComanda1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblComanda1.setForeground(new java.awt.Color(255, 255, 255));
        lblComanda1.setText("Comanda");
        lblComanda1.setPreferredSize(new java.awt.Dimension(190, 50));
        btnOrder.add(lblComanda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 108, 38));

        menuIzq.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 55));

        btnEmployees.setBackground(new java.awt.Color(209, 114, 28));
        btnEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployees.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEmployeesFocusGained(evt);
            }
        });
        btnEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmployeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmployeesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmployeesMousePressed(evt);
            }
        });
        btnEmployees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpleados.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleados.setText("Empleados");
        lblEmpleados.setPreferredSize(new java.awt.Dimension(190, 50));
        btnEmployees.add(lblEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 108, 38));

        iconEmployeelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMainWindow/iconEmployee.png"))); // NOI18N
        btnEmployees.add(iconEmployeelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        menuIzq.add(btnEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 55));

        btnClient.setBackground(new java.awt.Color(209, 114, 28));
        btnClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClientMousePressed(evt);
            }
        });
        btnClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClientes.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setText("Clientes");
        lblClientes.setPreferredSize(new java.awt.Dimension(190, 50));
        btnClient.add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 108, 38));

        iconClientlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMainWindow/iconClient.png"))); // NOI18N
        btnClient.add(iconClientlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        menuIzq.add(btnClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 55));

        btnProducts.setBackground(new java.awt.Color(209, 114, 28));
        btnProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProductsMousePressed(evt);
            }
        });
        btnProducts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductos.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblProductos.setText("Productos");
        lblProductos.setPreferredSize(new java.awt.Dimension(190, 50));
        btnProducts.add(lblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 108, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMainWindow/iconPizza.png"))); // NOI18N
        btnProducts.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        menuIzq.add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 210, 55));

        btnCloseS.setBackground(new java.awt.Color(209, 114, 28));
        btnCloseS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseSMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseSMousePressed(evt);
            }
        });
        btnCloseS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liblCloseS.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        liblCloseS.setForeground(new java.awt.Color(255, 255, 255));
        liblCloseS.setText("Cerrar Sesion");
        liblCloseS.setPreferredSize(new java.awt.Dimension(190, 50));
        btnCloseS.add(liblCloseS, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 10, 130, 38));

        iconExitlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMainWindow/iconExit.png"))); // NOI18N
        btnCloseS.add(iconExitlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        menuIzq.add(btnCloseS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 210, 55));

        lblUser.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("USER");
        menuIzq.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, -1, -1));

        iconUserlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMainWindow/iconUsuario.png"))); // NOI18N
        menuIzq.add(iconUserlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        btnMain.setBackground(new java.awt.Color(209, 114, 28));
        btnMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMainMousePressed(evt);
            }
        });
        btnMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMain.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lblMain.setForeground(new java.awt.Color(255, 255, 255));
        lblMain.setText("Principal");
        lblMain.setPreferredSize(new java.awt.Dimension(190, 50));
        btnMain.add(lblMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 108, 38));

        iconMainlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMainWindow/iconMain.png"))); // NOI18N
        btnMain.add(iconMainlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        menuIzq.add(btnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 210, 55));

        lblLetras.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        lblLetras.setForeground(new java.awt.Color(255, 255, 255));
        lblLetras.setText("MazPizza");
        menuIzq.add(lblLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        menuIzq.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, 10));

        jPanel1.add(menuIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 670));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(227, 136, 40));

        lblWelcome.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Bienvenido a la aplicación ");

        liblTextoM.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        liblTextoM.setForeground(new java.awt.Color(255, 255, 255));
        liblTextoM.setText("MazPizza");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(liblTextoM)
                    .addComponent(lblWelcome))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(liblTextoM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 700, 180));

        javax.swing.GroupLayout ReproductorLayout = new javax.swing.GroupLayout(Reproductor);
        Reproductor.setLayout(ReproductorLayout);
        ReproductorLayout.setHorizontalGroup(
            ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        ReproductorLayout.setVerticalGroup(
            ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanel1.add(Reproductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 700, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metodo para visualizar el panel del principal
    private void showView(JPanel openView)
    {
        openView.setSize(700, 490);
        openView.setLocation(0,0);
        
        Reproductor.removeAll();
        Reproductor.add(openView,BorderLayout.CENTER);
        Reproductor.revalidate();
        Reproductor.repaint();
    }
    
    private void btnSuppliesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuppliesMousePressed
        SuppliesView emp = new SuppliesView();
        showView(emp);
    }//GEN-LAST:event_btnSuppliesMousePressed

    private void btnSuppliesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuppliesMouseEntered
        //Asignación de un color cuando el mouse entra
        if(btnSupplies.getBackground().getRGB() == -15574355)
            setColor(btnSupplies);
    }//GEN-LAST:event_btnSuppliesMouseEntered

    private void btnSuppliesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuppliesMouseExited
        if(btnClient.getBackground().getRGB() != -15574355 || btnOrder.getBackground().getRGB() != -15574355|| btnProducts.getBackground().getRGB() != -15574355||
             btnEmployees.getBackground().getRGB() != -15574355)
            resetColor(btnSupplies);
    }//GEN-LAST:event_btnSuppliesMouseExited

    private void btnOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseEntered
        //Asignación de un color cuando el mouse entra
        if(btnOrder.getBackground().getRGB() == -15574355)
            setColor(btnOrder);
    }//GEN-LAST:event_btnOrderMouseEntered

    private void btnOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseExited
        if(btnClient.getBackground().getRGB() != -15574355 || btnSupplies.getBackground().getRGB() != -15574355|| btnProducts.getBackground().getRGB() != -15574355||
             btnEmployees.getBackground().getRGB() != -15574355)
            resetColor(btnOrder);
    }//GEN-LAST:event_btnOrderMouseExited

    private void btnOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMousePressed
        OrderView emp = new OrderView(employeeS);
        showView(emp);
        
        //new OrderView(employeeS).setVisible(true);
    }//GEN-LAST:event_btnOrderMousePressed

    private void btnEmployeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeesMouseEntered
        //Asignación de un color cuando el mouse entra
        if(btnEmployees.getBackground().getRGB() == -15574355)
            setColor(btnEmployees);
    }//GEN-LAST:event_btnEmployeesMouseEntered

    private void btnEmployeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeesMouseExited
        if(btnClient.getBackground().getRGB() != -15574355 || btnOrder.getBackground().getRGB() != -15574355|| btnProducts.getBackground().getRGB() != -15574355||
             btnSupplies.getBackground().getRGB() != -15574355)
            resetColor(btnEmployees);
    }//GEN-LAST:event_btnEmployeesMouseExited

    private void btnEmployeesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeesMousePressed
        EmployeeView emp = new EmployeeView();
        showView(emp);
    }//GEN-LAST:event_btnEmployeesMousePressed

    private void btnClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientMouseEntered
        //Asignación de un color cuando el mouse entra
        if(btnClient.getBackground().getRGB() == -15574355)
            setColor(btnClient);
    }//GEN-LAST:event_btnClientMouseEntered

    private void btnClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientMouseExited
        //Metodo que de color cuando el mouse salga
        if(btnEmployees.getBackground().getRGB() != -15574355 || btnOrder.getBackground().getRGB() != -15574355|| btnProducts.getBackground().getRGB() != -15574355||
             btnSupplies.getBackground().getRGB() != -15574355)
            resetColor(btnClient);
    }//GEN-LAST:event_btnClientMouseExited

    private void btnClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientMousePressed
        ClientView cli = new ClientView();
        showView(cli);
    }//GEN-LAST:event_btnClientMousePressed

    private void btnProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseEntered
         //Asignación de un color cuando el mouse entra
        if(btnProducts.getBackground().getRGB() == -15574355)
            setColor(btnProducts);
    }//GEN-LAST:event_btnProductsMouseEntered

    private void btnProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMouseExited
        //Metodo que de color cuando el mouse salga
        if(btnEmployees.getBackground().getRGB() != -15574355 || btnOrder.getBackground().getRGB() != -15574355|| btnClient.getBackground().getRGB() != -15574355||
             btnSupplies.getBackground().getRGB() != -15574355)
            resetColor(btnProducts);
    }//GEN-LAST:event_btnProductsMouseExited

    private void btnProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductsMousePressed
        ProductsView prod = new ProductsView();
        showView(prod);
    }//GEN-LAST:event_btnProductsMousePressed

    private void btnEmployeesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEmployeesFocusGained
        
    }//GEN-LAST:event_btnEmployeesFocusGained

    private void btnCloseSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSMouseClicked
        // TODO add your handling code here:
           //Metodo que nos ayuda a Cerrar la sesion
            int dialog = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null,"Esta Seguro que desea cerrar la Sesion ","Exit",dialog); //Dar un mensaje para verificar que desea salir
            
            if(result==0){
                Login acceso = new  Login();
                acceso.setVisible(true);
                dispose();
            }
    }//GEN-LAST:event_btnCloseSMouseClicked

    private void btnMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMousePressed
        // TODO add your handling code here:
        MainView mainw = new MainView();
        showView(mainw);
    }//GEN-LAST:event_btnMainMousePressed

    private void btnCloseSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseSMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        MainView mainw = new MainView();
        showView(mainw);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Reproductor;
    private javax.swing.JPanel btnClient;
    private javax.swing.JPanel btnCloseS;
    private javax.swing.JPanel btnEmployees;
    private javax.swing.JPanel btnMain;
    private javax.swing.JPanel btnOrder;
    private javax.swing.JPanel btnProducts;
    private javax.swing.JPanel btnSupplies;
    private javax.swing.JLabel iconClientlbl;
    private javax.swing.JLabel iconEmployeelbl;
    private javax.swing.JLabel iconExitlbl;
    private javax.swing.JLabel iconMainlbl;
    private javax.swing.JLabel iconOrderlbl;
    private javax.swing.JLabel iconSupplbl;
    private javax.swing.JLabel iconUserlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblComanda1;
    private javax.swing.JLabel lblEmpleados;
    private javax.swing.JLabel lblInsumos;
    private javax.swing.JLabel lblLetras;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel liblCloseS;
    private javax.swing.JLabel liblTextoM;
    private javax.swing.JPanel menuIzq;
    // End of variables declaration//GEN-END:variables

//Metodo que establece color 
    private void setColor(JPanel colorsito) {      
       btnSupplies.setBackground(new Color(255,175,0));
    }
    //Metodo para establecer color
    private void resetColor(JPanel colorsito) {
      btnSupplies.setBackground(new Color(209,114,28));
    }
}
 
