/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import static Controlador.OrderController.DeleteOrder;
import static Controlador.OrderController.GetOrdes;
import Controlador.ThreadController;
import static Controlador.ThreadController.ThreadController;
import Modelo.EmployeeModel;
import Modelo.OrderModel;
import Modelo.SuppliesModel;
import com.mysql.cj.util.StringUtils;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edwin
 */
public class OrderView extends javax.swing.JPanel {

    EmployeeModel employeeS = new EmployeeModel();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public OrderView(EmployeeModel employee) {
        initComponents();
        employeeS = employee;        
        GetData();
        ThreadController();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpd1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdOrder = new javax.swing.JTable();
        txtIdOrder = new javax.swing.JTextField();
        btnDeleteOrder = new javax.swing.JButton();
        btnAddOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTituloOrder = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpd1.setBackground(new java.awt.Color(204, 102, 11));
        btnUpd1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpd1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpd1.setText("Actualizar");
        btnUpd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        grdOrder.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        grdOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grdOrder.setSelectionBackground(new java.awt.Color(204, 102, 11));
        jScrollPane1.setViewportView(grdOrder);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 650, 360));

        txtIdOrder.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdOrderKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdOrderKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 150, 30));

        btnDeleteOrder.setBackground(new java.awt.Color(204, 102, 11));
        btnDeleteOrder.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDeleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteOrder.setText("Eliminar");
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 100, 30));

        btnAddOrder.setBackground(new java.awt.Color(204, 102, 11));
        btnAddOrder.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAddOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOrder.setText("Agregar");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, 30));

        jPanel2.setBackground(new java.awt.Color(204, 102, 11));

        lblTituloOrder.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTituloOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloOrder.setText("Apartado de Comandas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblTituloOrder)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTituloOrder)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpd1ActionPerformed
        modelo = new DefaultTableModel();
        grdOrder.setModel(modelo);
        
        GetData();
    }//GEN-LAST:event_btnUpd1ActionPerformed
    //Obtención de datos
    public void GetData(){
        ArrayList<OrderModel> orderList = GetOrdes();
        grdOrder.setModel(modelo);
        
        modelo.addColumn("idComanda");
        modelo.addColumn("Hora");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Atendio por");
        modelo.addColumn("Estatus");
        modelo.addColumn("Valor");
        
        for(OrderModel ord: orderList)
            {
                 Object[] filas2 = new Object[8];//9
                 filas2[0] = ord.idComanda;
                 filas2[1] = ord.Hora;
                 filas2[2] = ord.Fecha;
                 filas2[3] = ord.NombreCli;
                 filas2[4] = ord.NombreEmp;
                 filas2[5] = ord.Estatus;
                 filas2[6] = ord.Valor;
                 
                 modelo.addRow(filas2);
            }
    }
    
    private void txtIdOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdOrderKeyPressed

    }//GEN-LAST:event_txtIdOrderKeyPressed

    private void txtIdOrderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdOrderKeyTyped
        // Validación para que sólo se digiten numeros
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdOrderKeyTyped

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
       //Eliminación de datos de la orden (Comanda)
        int idOrder = Integer.parseInt(txtIdOrder.getText());

        boolean corret = DeleteOrder(idOrder);

        if(corret)
        {
            JOptionPane.showMessageDialog(null, "Se elimino el IdInOrder " +idOrder+ "correctamente.");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "La comanda no existe, intentelo de nuevo.");
        }
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
        new CreateOrderView(employeeS).setVisible(true);
    }//GEN-LAST:event_btnAddOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnUpd1;
    private javax.swing.JTable grdOrder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloOrder;
    private javax.swing.JTextField txtIdOrder;
    // End of variables declaration//GEN-END:variables

}
