/*
Nombre: Edwing Ricardo Rochin López
Descripción: Clase para agregar productos
Fecha: 15/09/2022
 */
package Vista;

import static Controlador.ProductsController.DeleteProduct;
import static Controlador.ProductsController.GetProduct;
import static Controlador.ProductsController.existsProduct;
import Modelo.ProductsModel;
import com.mysql.cj.util.StringUtils;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ProductsView extends javax.swing.JPanel {

    /**
     * Creates new form ProductsView
     */
    DefaultTableModel modelo = new DefaultTableModel();
    JTable tabla = new JTable(modelo);
   
    public ProductsView() {
        initComponents();
        
        GetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdProduct = new javax.swing.JTable();
        txtIdProducts = new javax.swing.JTextField();
        btnDeleteProducts = new javax.swing.JButton();
        btnUpdateProducts = new javax.swing.JButton();
        btnAddProducts = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTituloPro = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpd.setBackground(new java.awt.Color(204, 102, 11));
        btnUpd.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpd.setForeground(new java.awt.Color(255, 255, 255));
        btnUpd.setText("Actualizar");
        btnUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        grdProduct.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        grdProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grdProduct.setSelectionBackground(new java.awt.Color(204, 102, 11));
        jScrollPane1.setViewportView(grdProduct);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 650, 360));

        txtIdProducts.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdProductsKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 30));

        btnDeleteProducts.setBackground(new java.awt.Color(204, 102, 11));
        btnDeleteProducts.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDeleteProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteProducts.setText("Eliminar");
        btnDeleteProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductsActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 100, 30));

        btnUpdateProducts.setBackground(new java.awt.Color(204, 102, 11));
        btnUpdateProducts.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpdateProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateProducts.setText("Editar");
        btnUpdateProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductsActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 100, 30));

        btnAddProducts.setBackground(new java.awt.Color(204, 102, 11));
        btnAddProducts.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAddProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProducts.setText("Agregar");
        btnAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductsActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, 30));

        jPanel2.setBackground(new java.awt.Color(204, 102, 11));

        lblTituloPro.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTituloPro.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPro.setText("Apartado de Productos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTituloPro)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTituloPro)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProductsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProductsKeyTyped
        // TODO add your handling code here:
           int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdProductsKeyTyped
    //Obtención de datos
    public void GetData(){
        ArrayList<ProductsModel> productList = GetProduct();
        grdProduct.setModel(modelo);
        
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        
        for(ProductsModel pro: productList)
            {
                 Object[] filas2 = new Object[4];
                 filas2[0] = pro.idProductos;
                 filas2[1] = pro.NombreProducto;
                 filas2[2] = pro.Descripcion;
                 filas2[3] = pro.PrecioProducto;

                 
                 modelo.addRow(filas2);
            }
    }
    
    private void btnUpdateProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductsActionPerformed
        // Edición de datos en los productos
           int idProduct = 0;

        if(!StringUtils.isNullOrEmpty(txtIdProducts.getText()))
        {
            idProduct = Integer.parseInt(txtIdProducts.getText());

            ProductsModel products = existsProduct(idProduct);

            if(products.idProductos == idProduct){
                new CreateProductsView(products).setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "El producto que intentas editar no existe, intentelo de nuevo.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Es necesario ingresar un idProducto para editar.");
        }
    }//GEN-LAST:event_btnUpdateProductsActionPerformed

    private void btnDeleteProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductsActionPerformed
        // Eliminación de datos en los productos
        int idProduct = Integer.parseInt(txtIdProducts.getText());

        boolean corret = DeleteProduct(idProduct);

        if(corret)
        {
            JOptionPane.showMessageDialog(null, "Se elimino el IdProducto " +idProduct+ "correctamente.");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "El producto no existe, intentelo de nuevo.");
        }
    }//GEN-LAST:event_btnDeleteProductsActionPerformed

    private void btnAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductsActionPerformed
        // TODO add your handling code here:
        new CreateProductsView().setVisible(true);
    }//GEN-LAST:event_btnAddProductsActionPerformed

    private void btnUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdActionPerformed
        modelo = new DefaultTableModel();
        grdProduct.setModel(modelo);
        
        GetData();
    }//GEN-LAST:event_btnUpdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProducts;
    private javax.swing.JButton btnDeleteProducts;
    private javax.swing.JButton btnUpd;
    private javax.swing.JButton btnUpdateProducts;
    private javax.swing.JTable grdProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloPro;
    private javax.swing.JTextField txtIdProducts;
    // End of variables declaration//GEN-END:variables
}
