/*
Nombre: Edwing Ricardo Rochin López
Descripción: Clase para agregar insumos
Fecha: 15/09/2022
 */
package Vista;

import static Controlador.SuppliesController.DeleteSupplies;
import static Controlador.SuppliesController.GetSupplies;
import static Controlador.SuppliesController.existsSupplies;
import Modelo.SuppliesModel;
import com.mysql.cj.util.StringUtils;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edwin
 */
public class SuppliesView extends javax.swing.JPanel {

    /**
     * Creates new form SuppliesView
     */
    DefaultTableModel modelo = new DefaultTableModel();
    JTable tabla = new JTable(modelo);
    
    public SuppliesView() {
        initComponents();
        
        GetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUpdateI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdSupplies = new javax.swing.JTable();
        btnDeleteI = new javax.swing.JButton();
        btnUpdSupp = new javax.swing.JButton();
        txtIdInsumo = new javax.swing.JTextField();
        btnAddSupplies = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTituloSupp = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateI.setBackground(new java.awt.Color(204, 102, 11));
        btnUpdateI.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpdateI.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateI.setText("Editar");
        btnUpdateI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateIActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateI, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 100, 30));

        grdSupplies.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        grdSupplies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grdSupplies.setSelectionBackground(new java.awt.Color(204, 102, 11));
        jScrollPane1.setViewportView(grdSupplies);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 650, 360));

        btnDeleteI.setBackground(new java.awt.Color(204, 102, 11));
        btnDeleteI.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDeleteI.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteI.setText("Eliminar");
        btnDeleteI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteIActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 100, 30));

        btnUpdSupp.setBackground(new java.awt.Color(204, 102, 11));
        btnUpdSupp.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpdSupp.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdSupp.setText("Actualizar");
        btnUpdSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdSuppActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        txtIdInsumo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdInsumo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdInsumoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdInsumoKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 30));

        btnAddSupplies.setBackground(new java.awt.Color(204, 102, 11));
        btnAddSupplies.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAddSupplies.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSupplies.setText("Agregar");
        btnAddSupplies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSuppliesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddSupplies, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, 30));

        jPanel2.setBackground(new java.awt.Color(204, 102, 11));

        lblTituloSupp.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTituloSupp.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSupp.setText("Apartado de Insumos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblTituloSupp)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblTituloSupp)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));
    }// </editor-fold>//GEN-END:initComponents
    //Obtención de datos
    public void GetData(){
        ArrayList<SuppliesModel> suppliesList = GetSupplies();
        grdSupplies.setModel(modelo);
        
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Costo");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio porción");
        modelo.addColumn("Es ingrediente");
        
        
        for(SuppliesModel sup: suppliesList)
            {   
                String Es = "No";
                if(sup.EsIngrediente){
                    Es = "Si";
                }
                 Object[] filas2 = new Object[6];
                 filas2[0] = sup.idInsumos;
                 filas2[1] = sup.NombreInsumo;
                 filas2[2] = sup.PrecioI;
                 filas2[3] = sup.descripcionI;
                 filas2[4] = sup.PrecioPorcion;
                 filas2[5] = Es;
                 
                 modelo.addRow(filas2);
            }
    }
    
    private void btnUpdateIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateIActionPerformed
        //Edición de datos
        int idSupplie = 0;

        if(!StringUtils.isNullOrEmpty(txtIdInsumo.getText()))
        {
            idSupplie = Integer.parseInt(txtIdInsumo.getText());

            SuppliesModel supplies = existsSupplies(idSupplie);

            if(supplies.idInsumos == idSupplie){
                new CreateSuppliesView(supplies).setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "El insumo que intentas editar no existe, intentelo de nuevo.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Es necesario ingresar un idInsumo para editar.");
        }
    }//GEN-LAST:event_btnUpdateIActionPerformed

    private void btnDeleteIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIActionPerformed
        //Eliminación de datos
        int idSupplie = Integer.parseInt(txtIdInsumo.getText());

        boolean corret = DeleteSupplies(idSupplie);

        if(corret)
        {
            JOptionPane.showMessageDialog(null, "Se elimino el IdInsumo " +idSupplie+ "correctamente.");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "El insumo no existe, intentelo de nuevo.");
        }
    }//GEN-LAST:event_btnDeleteIActionPerformed

    private void btnUpdSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdSuppActionPerformed
        modelo = new DefaultTableModel();
        grdSupplies.setModel(modelo);
        
        GetData();
    }//GEN-LAST:event_btnUpdSuppActionPerformed

    private void txtIdInsumoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdInsumoKeyPressed

    }//GEN-LAST:event_txtIdInsumoKeyPressed

    private void txtIdInsumoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdInsumoKeyTyped
        // Validación para digitar sólo numeros
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdInsumoKeyTyped

    private void btnAddSuppliesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSuppliesActionPerformed
        // TODO add your handling code here:
        new CreateSuppliesView().setVisible(true);
    }//GEN-LAST:event_btnAddSuppliesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplies;
    private javax.swing.JButton btnDeleteI;
    private javax.swing.JButton btnUpdSupp;
    private javax.swing.JButton btnUpdateI;
    private javax.swing.JTable grdSupplies;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloSupp;
    private javax.swing.JTextField txtIdInsumo;
    // End of variables declaration//GEN-END:variables
}
